port: :8081
weather:
  apiurl: https://api.open-meteo.com/v1/forecast
kitchenowl:
  apiurl: https://your-kitchenowl-instance/api
  token: your-token
  householdid: 1
ical:
  calendars:
    - name: "Personal"
      url: "https://example.com/calendar.ics"
vcf:
  path: /path/to/contacts.vcf
simplemarkdown:
  path: /path/to/markdown/files
